pipeline module, improvement may needed
krezelj/wb-active-learning pull request #15
Opened 2023-04-24 19:47 UTC by Szymon-Gut

2023-04-24 20:22 UTC, maciejors commented
ratio_classes looks good to me now. good job on that

`train_loader` and `test_loader` were missing from `Pipeline.__slots__` which was causing an error. I added them there.

Now I'm getting a new error:
![image](https://user-images.githubusercontent.com/61619870/234107486-da6cf74e-e403-4895-9bc4-ea8cf5258756.png)
not sure what causes it, perhaps the parameter values of `n_queries=10, init_epochs=100, epochs_per_query=100` that I'm passing here don't make sense but idk.

edit: This code should reproduce the error (I run it in a notebook):
```py
%load_ext autoreload
%autoreload 2

import sys
sys.path.append("../..")

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

import src.modules.data_module as dm
import src.modules.learner_module as lm
import src.models as models
import src.modules.pipeline as pp

device = 'cpu'

# unified test set
test_size = 1000
ds_test = dm.ActiveDataset('mnist', 0, test_size, balanced_split=False)
test_loader = DataLoader(ds_test.test_set, batch_size=128)

init_samples = 100
train_size = 10000
loss_fn = F.cross_entropy

# init learner
model = models.MNISTClassifier().to(device)
learner = lm.ActiveLearner(model, device)
optimizer = torch.optim.Adam(params=model.parameters())

# init set
ds = dm.ActiveDataset('mnist', train_size, 0, ratio_labeled=init_samples/train_size, balanced_split=False)

pipe = pp.Pipeline()
pipe.fit_transform(data_set=ds, learner=learner, optimizer=optimizer, loss_function=loss_fn, n_queries=5, init_epochs=1000, epochs_per_query=1000, query_batch_size=500)
```

2023-04-25 09:14 UTC, krezelj commented
I believe it might be the case that you have test_size set to 0 and use the generated (empty) test set to create a test_loader that is then passed to `learner.fit()` method. No validation loss is calculated and so `i` is not declared in the loop which causes the error. This concerns the learner module, I'll create an issue for it.

2023-04-25 09:27 UTC, krezelj requested changes

2023-04-25 09:27 UTC, krezelj commented on src/modules/pipeline.py
As per my comment on the group chat the Pipeline should be simpler:
- use `__init__` to set variables like `ds : ActiveDataset`, `learner: ActiveLearner`, `n_queries`, `queries_per_batch` etc.
    - might be useful to implement `PipelineSettings` class that holds all settings (apart from `ds` and `learner` and allows for writing/reading to/from .json file 
- implement `run` method that runs the pipeline on the set variables and outputs `em.Session` object.
    - apart from `em.Session` it might also return a dict of stats containing things like `t_loss_history`, `v_loss_history`, `accuracy_history` etc.
- get rid of `fit`, `transform`, `fit_transform` methods

2023-04-25 09:27 UTC, krezelj commented on src/modules/data_module.py
Looks good

2023-04-25 16:25 UTC, maciejors commented
`Pipeline` class is now implemented with all the changes requested. The `run()` method mostly reuses the code that was earlier inside the old `transform()` method.

I also added `PipelineSettings` class as suggested. It supports exporting/importing to/from dict and json files.

2023-04-25 18:41 UTC, krezelj requested changes
Looks really good. Good job on the PipelineSettings. A few QOL suggestions.

2023-04-25 18:41 UTC, krezelj commented on src/modules/pipeline.py
> +                criterion='entropy',
Make this a parameter of PipelineSettings. Possible values: `confidence`, `margin`, `entropy`, `random`.

2023-04-25 18:41 UTC, krezelj commented on src/modules/pipeline.py
> +            print(f"Max uncertainty: {uncertainty}")
Add `verbose` as parameter of run default is 0. If `verbose>1` display max uncertainites.

2023-04-25 18:41 UTC, krezelj commented on src/modules/pipeline.py
> +            print(f"Iteration: {i+1}")
Add `verbose` as parameter of run default is 0. If `verbose>0` display current iteration

2023-04-25 18:41 UTC, krezelj commented on src/modules/pipeline.py
> +        }
Add `f1_score_history` as one of the returned stats. Add parameters to `run` function:
- `calculate_accuracy=False`
    - only calculate accuracy if True (to speed up computation)
- `calculate_f1_score=False`
    - same as above

2023-04-25 18:41 UTC, krezelj commented on src/modules/pipeline.py
> +        )
Pipeline already has slot `test_loader` that is set in `__init__`. When calling this function we pass `self.test_loader` anyway so I would get rid of this parameter and use `self.test_loader` inside the functions instead.

```suggestion
    def _calculate_f1_score(self):
        outputs = self.learner.predict(self.test_loader)
        return multiclass_f1_score(
            outputs,
            self.test_loader.dataset.dataset.targets[self.test_loader.dataset.indices]
        )

    def _calculate_accuracy(self):
        outputs = self.learner.predict(self.test_loader)
        return multiclass_accuracy(
            outputs,
            self.test_loader.dataset.dataset.targets[self.test_loader.dataset.indices]
        )
```

2023-04-25 19:25 UTC, maciejors commented
all done and tested

2023-04-25 19:31 UTC, krezelj approved these changes
Great thanks, approved

2023-04-25 19:31 UTC, merged